version: "3.8"

services:
  backend:
    container_name: chatbot
    build: backend
    ports:
      - "8000:8000"
    env_file:
      - backend/.env
    depends_on:
      - postgres
      - minio
    networks:
      - chatbot
    volumes:
      - ./backend/:/app

  postgres:
    image: pgvector/pgvector:pg17
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=chatbot
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - chatbot
    ports:
      - "5432:5432"

  minio:
    image: minio/minio:RELEASE.2025-03-12T18-04-18Z
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - chatbot
    command: server --console-address ":9001" /data

  web:
    container_name: web
    build: frontend
    ports:
      - "3000:3000"
    networks:
      - chatbot

networks:
  chatbot:

volumes:
  pgdata:
  minio_data:
