"""Add url and time Models Upload

Revision ID: 24fe124fa291
Revises: 36556c2e7a2e
Create Date: 2025-04-21 06:27:40.510829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '24fe124fa291'
down_revision: Union[str, None] = '36556c2e7a2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('embedding_files', sa.Column(
        'url', sa.String(length=255), nullable=True))
    op.add_column('embedding_files', sa.Column(
        'url_expire_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('embedding_files', 'url_expire_time')
    op.drop_column('embedding_files', 'url')
    # ### end Alembic commands ###
