"""init db

Revision ID: 30732418d8d2
Revises: 
Create Date: 2025-03-24 04:18:37.050121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30732418d8d2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_histories',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('talk_title', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('delete_flag', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_history_details',
    sa.Column('chat_histories_id', sa.Integer(), nullable=False),
    sa.Column('talk_at', sa.DateTime(), nullable=False),
    sa.Column('question_content', sa.String(), nullable=False),
    sa.Column('answer_content', sa.String(), nullable=False),
    sa.Column('talk_evaluation', sa.SmallInteger(), nullable=True),
    sa.Column('reference_file', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('delete_flag', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('embedding_files',
    sa.Column('objects_name', sa.String(length=255), nullable=False),
    sa.Column('objects_update_dt', sa.DateTime(), nullable=False),
    sa.Column('last_embedding_dt', sa.DateTime(), nullable=True),
    sa.Column('embedding_reserve_date', sa.DateTime(), nullable=True),
    sa.Column('embedding_status', sa.SmallInteger(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('delete_flag', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('google_auth_flg', sa.Boolean(), nullable=True),
    sa.Column('init_lpassword_chang_flg', sa.Boolean(), nullable=True),
    sa.Column('change_password_flg', sa.Boolean(), nullable=True),
    sa.Column('change_password_hash', sa.String(length=255), nullable=True),
    sa.Column('change_password_dt', sa.DateTime(), nullable=True),
    sa.Column('role', sa.SmallInteger(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('delete_flag', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('embedding_files')
    op.drop_table('chat_history_details')
    op.drop_table('chat_histories')
    # ### end Alembic commands ###
