"""Fix id in chat table

Revision ID: 4805a7a25590
Revises: e743b4c86088
Create Date: 2025-07-01 06:29:08.702420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4805a7a25590'
down_revision: Union[str, None] = 'e743b4c86088'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_histories', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('chat_histories', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('chat_history_details', 'chat_histories_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('chat_history_details', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_by',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('embedding_files', 'created_by',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('chat_history_details', 'created_by',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('chat_history_details', 'id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('chat_history_details', 'chat_histories_id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('chat_histories', 'created_by',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('chat_histories', 'id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('chat_histories', 'user_id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
