"""add field is_error embedding

Revision ID: 533ef23df629
Revises: cb5f30dce48d
Create Date: 2025-07-16 04:16:42.041922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '533ef23df629'
down_revision: Union[str, None] = 'cb5f30dce48d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('embedding_files', sa.Column('is_error', sa.Boolean(), nullable=True, comment='Indicates if the upload has an error'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('embedding_files', 'is_error')
    # ### end Alembic commands ###
