"""Add more table, migration to share file

Revision ID: 62c20dc27fd4
Revises: 24fe124fa291
Create Date: 2025-05-26 04:32:28.355883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62c20dc27fd4'
down_revision: Union[str, None] = '24fe124fa291'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('delete_flag', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('permissions',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('delete_flag', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('folders',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('delete_flag', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['folders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('access_control_entry',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('folder_id', sa.Integer(), nullable=True),
    sa.Column('file_id', sa.Integer(), nullable=True),
    sa.Column('permission_type_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('delete_flag', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['file_id'], ['embedding_files.id'], ),
    sa.ForeignKeyConstraint(['folder_id'], ['folders.id'], ),
    sa.ForeignKeyConstraint(['permission_type_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('department_id', 'file_id', 'permission_type_id', name='uq_dept_file_permission'),
    sa.UniqueConstraint('department_id', 'folder_id', 'permission_type_id', name='uq_dept_folder_permission'),
    sa.UniqueConstraint('user_id', 'file_id', 'permission_type_id', name='uq_user_file_permission'),
    sa.UniqueConstraint('user_id', 'folder_id', 'permission_type_id', name='uq_user_folder_permission')
    )
    op.create_index('ix_department_id', 'access_control_entry', ['department_id'], unique=False)
    op.create_index('ix_file_id', 'access_control_entry', ['file_id'], unique=False)
    op.create_index('ix_folder_id', 'access_control_entry', ['folder_id'], unique=False)
    op.create_index('ix_user_id', 'access_control_entry', ['user_id'], unique=False)
    op.add_column('embedding_files', sa.Column('folder_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'embedding_files', 'folders', ['folder_id'], ['id'])
    op.add_column('users', sa.Column('department_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'departments', ['department_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'department_id')
    op.drop_constraint(None, 'embedding_files', type_='foreignkey')
    op.drop_column('embedding_files', 'folder_id')
    op.drop_index('ix_user_id', table_name='access_control_entry')
    op.drop_index('ix_folder_id', table_name='access_control_entry')
    op.drop_index('ix_file_id', table_name='access_control_entry')
    op.drop_index('ix_department_id', table_name='access_control_entry')
    op.drop_table('access_control_entry')
    op.drop_table('folders')
    op.drop_table('permissions')
    op.drop_table('departments')
    # ### end Alembic commands ###
