"""create notification

Revision ID: cb5f30dce48d
Revises: 4805a7a25590
Create Date: 2025-07-10 04:35:21.734191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cb5f30dce48d'
down_revision: Union[str, None] = '4805a7a25590'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_badges',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('unread_count', sa.Integer(), nullable=True),
    sa.Column('last_notification_dt', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('delete_flag', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.String(length=1024), nullable=False),
    sa.Column('read_flg', sa.Boolean(), nullable=True),
    sa.Column('file_id', sa.String(length=36), nullable=True),
    sa.Column('folder_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('delete_flag', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('chat_histories', 'created_by',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('chat_history_details', 'created_by',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('embedding_files', 'created_by',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('users', 'created_by',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_by',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('embedding_files', 'created_by',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('chat_history_details', 'created_by',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('chat_histories', 'created_by',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.drop_table('notifications')
    op.drop_table('notification_badges')
    # ### end Alembic commands ###
